### PR TITLE
Added support for Shipping API V2

### PR DESCRIPTION
**Pull request by IamGanesh19**
Tried and added support for Shipping API V2 in to this project. Associated issue - https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/274

### CODE REVIEW

**Comment by abuzuhri** [comment]
Hi @IamGanesh19 

Can you fix the changes

**Comment by IamGanesh19** [comment]
> Hi @IamGanesh19
> 
> Can you fix the changes

@abuzuhri, please let me know the changes which are to be fixed? I am not sure what is expected to be changed. Can you please eloborate?

**Comment by ebgtestdotnet** [comment]
"Source/FikaAmazonAPI/AmazonSpApiSDK/Models/ShippingV2/RequestedDocumentSpecification.cs" Please check Property type from documentations and change it accordingly. for e.g. _Format_ should be accepting string value like. PNG, PDF, etc.

**Comment by abuzuhri** [comment]
@IamGanesh19 please check

**Pull request merged**
