### PR TITLE
Async api request

### PR DESCRIPTION
**Pull request by J-W-Chan**

### CODE REVIEW

**Comment by abuzuhri** [comment]
Thanks @J-W-Chan

**Comment by abuzuhri** [comment]
Hello @J-W-Chan 

Async completed for all system

**Comment by J-W-Chan** [comment]
> Hello @J-W-Chan
> 
> Async completed for all system

Great. Hope this project gets better and better ！

**Comment by jsaxdev** [comment]
Who thought of adding  .GetAwaiter().GetResult() in non-async methods ? Which is bad practice and deadlocks can occur. Thanks for this one because my application now deadlocks on these methods.

**Comment by abuzuhri** [comment]
> Who thought of adding .GetAwaiter().GetResult() in non-async methods ? Which is bad practice and deadlocks can occur. Thanks for this one because my application now deadlocks on these methods.

try to do like this until problem solve
var orders= Task.Run(() => amazonConnection.Orders.GetOrdersAsync(serachOrderList)).ConfigureAwait(false).GetAwaiter().GetResult();

**Comment by abuzuhri** [comment]
its work if we remove Task.run like this

var orders=
amazonConnection.Orders.GetOrdersAsync(serachOrderList).ConfigureAwait(false).GetAwaiter().GetResult();
instead of

var orders= Task.Run(() =>
amazonConnection.Orders.GetOrdersAsync(serachOrderList)).ConfigureAwait(false).GetAwaiter().GetResult();


Can you try and let me know

**Pull request merged**
