### PR TITLE
Static httpc client

### PR DESCRIPTION
**Pull request by J-W-Chan**

### CODE REVIEW

**Comment by J-W-Chan** [comment]
@abuzuhri Can I merge this branch code into main branch?

**Comment by abuzuhri** [comment]
I do it now ,
I'm not sour if its will work with you , because the key to publish depending on my account

**Comment by abuzuhri** [comment]
its ready on v1.5.35

**Comment by abuzuhri** [comment]
@J-W-Chan we have many issue , we can look on it this weekend together if you free

**Comment by J-W-Chan** [comment]
> @J-W-Chan we have many issue , we can look on it this weekend together if you free

Make .Net Great Again!😀

**Comment by J-W-Chan** [comment]
> @J-W-Chan we have many issue , we can look on it this weekend together if you free


I am interested in participating in this job, but my English level is not very good.

**Pull request merged**
