### PR TITLE
X_Amzn_RequestId included in AmazonException

### PR DESCRIPTION
**Pull request by qaisarikram**
Recently I opened the [issue](https://github.com/abuzuhri/Amazon-SP-API-CSharp/issues/486) and you said "this error is from Amazon".
So I opened a Support ticket with Amazon Support and they have asked to provide them few things.
Out of those few things, following 2 are related to your Library.

a) The Timestamp (available in the request)
b) The Request ID (available in the response)

Point a:
I have added the **x-amzn-RequestId** in **AmazonException** Class.

Point b:
Please suggest how I can get the Timestamp from request?

### CODE REVIEW

**Comment by RenzoF** [comment]
Ho @qaisarikram, you should be able to get the information using the LastResponseHeader, have you tried that?

**Comment by qaisarikram** [comment]
> Hi @qaisarikram, you should be able to get the information using the LastResponseHeader, have you tried that?

Hi @RenzoF , thank you for replying.
I tried LastResponseHeader, I tired as shown below:
_var lastResponseHeader = amazonConnection.Services.LastResponseHeader;_

**amazonConnection.Services.LastResponseHeader is NULL**, am I using it correctly? if not, then can you please guide.
Thanks in advance

**Comment by RenzoF** [comment]
Are you calling it after catching the exception? 
Also you should call it from the service you made the call with eg: 
amazonconnection.FeedService.GetFeed(param);
amazonconnection.FeedService.GetFeed(
var headers =  amazonConnection.Services.LastResponseHeader;
Otherwise if just do it at anytime it makes sense that is null since you did not do a last call that run

**Comment by qaisarikram** [comment]
> Are you calling it after catching the exception? Also you should call it from the service you made the call with eg: amazonconnection.FeedService.GetFeed(param); amazonconnection.FeedService.GetFeed( var headers = amazonConnection.Services.LastResponseHeader; Otherwise if just do it at anytime it makes sense that is null since you did not do a last call that run

Yes, I am calling after catching exception.
below is the code that I am using
 
try
            {
                ParameterGetItemOffers GetItemOffer = new ParameterGetItemOffers()
                { 
                    ItemCondition = ItemCondition.New, 
                    MarketplaceId = MarketPlace.UnitedArabEmirates.ID, 
                    Asin = asin, CustomerType = CustomerType.Business 
                };

                var itemOffers = amazonConnection.ProductPricing.GetItemOffers(GetItemOffer);
            }

            catch (AmazonException amzEx)
            {
                var lastResponseHeader = amazonConnection.Services.LastResponseHeader;
            }

**Comment by RenzoF** [comment]
Try with amazonConnection.ProductPricing.LastReponseHeather

**Comment by qaisarikram** [comment]
> Try with amazonConnection.ProductPricing.LastReponseHeather

Great, that looks to be working!
image

Thank You Renzo for usual help :)

I can now probably fetch the **Date** and **x-amzn-requestId** in case of Error and send to Amazon Support.

**Comment by qaisarikram** [comment]
@RenzoF these are the info that Amazon Dev Support asked us to provide.

image

The very last one ""The Request ID", we just have sorted using LastResponseHeader.
Any idea if we can also fetch the **The Timestamp (available in the request)** ???

**Comment by RenzoF** [comment]
That I am not sure my guess is that the date you get in the array[0] should be good, though never opened a case, so not sure

**Comment by qaisarikram** [comment]
> That I am not sure my guess is that the date you get in the array[0] should be good, though never opened a case, so not sure

I also thought get get date from array[0], but that is Response DateTime, we need Request DateTime

**Comment by RenzoF** [comment]
Ok after looking a bit further I can see that a timestamp is added to the request headers when is signed the harder name is "X-Amz-Date". 
It looks like if you enable debug in your connection it should be logged in the console, That will be your fastest way to get it, I guess, for the future might be worth adding a method to get the LastRequestHeaders, @abuzuhri what do you think?

**Comment by qaisarikram** [comment]
> Ok after looking a bit further I can see that a timestamp is added to the request headers when is signed the harder name is "X-Amz-Date". It looks like if you enable debug in your connection it should be logged in the console, That will be your fastest way to get it, I guess, for the future might be worth adding a method to get the LastRequestHeaders, @abuzuhri what do you think?

Yeh, maybe I can get from console, but the issue is, the error is not coming with every request. It is coming randomly.
I'm logging the error (in API response) in logs and from there I will see the **RequestId** (that we already have fetched from LastResponseHeader) and also **TimeStamp** (we send in Request header)

**Comment by TechyChap** [comment]
> That I am not sure my guess is that the date you get in the array[0] should be good, though never opened a case, so not sure

Yes, that timestamp is good enough for Amazon.

**Comment by qaisarikram** [comment]
> > That I am not sure my guess is that the date you get in the array[0] should be good, though never opened a case, so not sure
> 
> Yes, that timestamp is good enough for Amazon.

Yep, I already have logged that timestamp in the logs and I can fetch that, Thank You.

I am only looking for one more thing ( that I hope that is final piece to complete the data to provide to amazon), they need "A copy of request and the response you received, not truncated and attached as .txt document". I have response but not request, I have only Parameters that I can provide.

Can you please help in this regard (If possible to get the request data) ?

**Comment by TechyChap** [comment]
I've logged this with our account manager too to see if they can clarify what they are asking for. I does seem like they are stalling, I've mentioned in one ticket that I was using the "UK" market and they responded that I'd not provided the ID for the marketplace. You'd expect them to know their own IDs.

**Pull request closed without merging**
