### PR TITLE
Updated NotificationMessages.Offer and NotificationMessages.OfferElement

### PR DESCRIPTION
**Pull request by CrineTech**
Changes related to notification classes, please expand commit description to see detailed informations on each change

### CODE REVIEW

**Comment by abuzuhri** [comment]
Thanks too much for that work

Can you add also Sample code and edit readme file https://github.com/abuzuhri/Amazon-SP-API-CSharp#notifications-create-destination-for-more-notifications-sample-please-check-here

**Comment by abuzuhri** [comment]
will be in v1.4.0

**Comment by CrineTech** [comment]
Thank you too, to start building and share this library. I hope to be able to share more changes in the future!

The only missing thing (was already in the code but missing from samples and readme) was the CreateSubscription.
I've added it in the last commit.

My code changes a lot of things in FikaAmazonAPI.NotificationMessages namespace, basically because all the classes putted here to handle the B2BAnyOfferChangedNotification where only placeholders, in most cases duplicated from the AnyOfferChangedNotification, but the two notification formats are quite different.

I don't think that there is more to add in readme / samples, now it will be also a lot easier to understand the fields meaning while coding, since intellisense will show field descriptions copied from Amazon official docs.

Please note that my commits have changed quite a bit the classes related to the AnyOfferChangedNotification and B2BAnyOfferChangedNotification, introducing some breaking changes. 

By looking at this library, it seems that there is so much work to do, so it should't be that bad to make some breaking changes to make code better. Moreover, i think that no one was using the B2BAnyOfferChangedNotification before me, since it was almost useless before of those changes.

**Comment by abuzuhri** [comment]
Thanks a lot for your help and you welcome in future to add more features

**Pull request merged**
