### PR TITLE
Vendor orders2

### PR DESCRIPTION
**Pull request by dave-sewell**
Add rate limit definitions for VendorOrders functions.

### CODE REVIEW

**Comment by abuzuhri** [comment]
@dave-sewell can you please merge to master to fix build error

**Comment by dave-sewell** [comment]
What do I need to do to "merge to master"?
I merged my local commits but the pull request for the merged commits is not causing another build to happen.
I don't know how to fix the remote build error. It does not happen locally.

**Comment by abuzuhri** [comment]
just get lasterest from our branch and you will get same problem

**Comment by dave-sewell** [comment]
Got it. I fixed the issue and submitted another pull request.

**Review by abuzuhri — APPROVED** [review]

**Comment by abuzuhri** [comment]
@dave-sewell  can you share also sample code in sample project

**Pull request merged**
