### PR TITLE
Fix broken links to samples

### PR DESCRIPTION
**Pull request by GuybrushX**
Please check if that are the samples you wanted to link to :-)

### CODE REVIEW

**Comment by abuzuhri** [comment]
Thanks for fix

**Comment by GuybrushX** [comment]
Welcome but... you didn't merge my commit? Did you forget that step or are my links wrong?

**Comment by abuzuhri** [comment]
Hi @GuybrushX 

I just noticed that I don’t accept the your request by mistake, it’s open to resubmit it again ?

**Comment by GuybrushX** [comment]
Hi,

I think I've deleted the previous fork and created a new fork in the meantime. But it seems that you can check this PR and still see the changes if you check the "Files changed".

Please let me know if you need a new PR but I think the changes are easy enough to just fix it yourself in your repo.

**Pull request closed without merging**
